# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
  ############################################################################                  
  #####################           Global Configs         #####################
  ############################################################################ 

  ####
  ## OS for all VMs
  ####

  config.vm.box = "ubuntu/trusty64"

  ####
  ## Init modules for all VMs
  ## Will be executed BEFORE any other manifests
  ####

  config.vm.provision "shell",
    inline: "sudo apt-get update -y"

  ####
  ## Memory usage for the Vms
  ####

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus   = 1
  end

  ############################################################################                  
  ########################          VM Configs         #######################
  ############################################################################    

  ####
  ## base box for testing
  ####

  config.vm.define "server" do |server|

    server.vm.network "forwarded_port", guest: "80", host: "1028", host_ip: "127.0.0.1"
    server.vm.network "private_network", ip: "10.2.2.2"

  end
  

end
